### ISSUE TITLE
Error: Cannot find module '../'

### ISSUE THREAD

**Issue by trailsandtribulations** [kudos/koa-websocket#1]
from your example

<pre>
const koa = require('koa'),
  route = require('koa-route'),
  websockify = require('../');
</pre>

returns error

<pre>
Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    ...
</pre>

**Comment by kudos** [comment]
Thanks for the report. I somehow unwatched this repo so got no notification, sorry about that!
