### ISSUE TITLE
no session

### ISSUE THREAD

**Issue by ryuken** [kudos/koa-websocket#10]
The session from koa-generic-session etc doesn't exist on the websocket side

**Comment by hedgerh** [comment]
For anyone else wondering, I believe you need to pass the session store to both `app.use` and `app.ws.use`.  The websocket object seems to have middleware separate from the koa app.

**Comment by chovy** [comment]
can you add example to doc?

**Comment by hedgerh** [comment]
@chovy:  Sure.  Are you a maintainer of this project or are you interested in the solution? just curious :)

**Comment by chovy** [comment]
@hedgerh i'm interested in the  solution -- I'm waiting for this module to support koa-router@7.0.1

**Comment by hedgerh** [comment]
@chovy: https://github.com/hedgerh/koa-websocket/blob/00168026e31d6f338ceee0157604e44b0e25b4f7/README.md

i may look into why its not working with `koa-router` next

**Comment by chovy** [comment]
The only comment I have on your example for routes is you might want to put a fake route like `/foo` so you can see how `/foo` is mapped on the backend and the front-end. It wasn't obvious at first glance how you use the route on the client side.
