### ISSUE TITLE
Using the socket variable from "var socket = websockify(app);" koa example?

### ISSUE THREAD

**Issue by donjae** [kudos/koa-websocket#17]
**From the koa router example, what's the socket variable used for?**
```
var koa = require('koa');  
var websockify = require('koa-websocket');
var router = require('koa-router');
var app = koa();

var api = router();
**var socket = websockify(app);**

api.get('/*', function* (next) {
  this.websocket.send('Hello World');
  this.websocket.on('message', function(message) {
    console.log(message);
  });
});

app.ws.use(api.routes()).use(api.allowedMethods());
app.listen(3000);
```
#

**Comment by kudos** [comment]
It's actually superfluous, `websockify` modifies the app variable that is passed to it, it then returns the app variable. This allows chaining but we're not using that here.

**Comment by donjae** [comment]
So would something like `socket.{someWebsocketMethod}` work?

**Comment by kudos** [comment]
`socket` is poorly named, it is a copy of `app`. An example of how you might chain things:

```js
var app = websockify(koa());
```

That's why it returns the same object it receives. I'll update the example to be more clear.
