### ISSUE TITLE
Access to the WebSocketServer?

### ISSUE THREAD

**Issue by bryanberger** [kudos/koa-websocket#19]
Having trouble trying to access the instantiated WebSocketServer in order to loop over all clients and broadcast, similarly to the example in the `ws` documentation:

```
wss.broadcast = function broadcast(data) {
  wss.clients.forEach(function each(client) {
    client.send(data);
  });
};
```

How would you gain access to the clients list?

**Comment by bryanberger** [comment]
Update: You can access the WSS from `app.ws.server.clients`

**Comment by prakasa1904** [comment]
no object on that. is this app koa or ctx.websocket for `app` ?
