### ISSUE TITLE
No Possibility to provide Options

### ISSUE THREAD

**Issue by vanthome** [kudos/koa-websocket#22]
I would like to pass an options object to the ` new WebSocketServer()` call.
As far as I see, this is impossible currently. I think it needs to be enabled here by a second param:

https://github.com/kudos/koa-websocket/blob/next/index.js#L15

**Comment by kudos** [comment]
@vanthome makes sense. Can you open a PR with the change?

**Comment by tangxinfa** [comment]
I created a PR(https://github.com/kudos/koa-websocket/pull/28), please have a look:)
