### ISSUE TITLE
How to create https server and support websocket or wss use koa2? 

### ISSUE THREAD

**Issue by SteveCruise** [kudos/koa-websocket#29]
Create https server:
```js
const Koa = require('koa');
const app = new Koa();
const options = {
    key: fs.readFileSync('./ssl/private.pem', 'utf8'),
    cert: fs.readFileSync('./ssl/20180303.crt', 'utf8')
};
https.createServer(options, app.callback()).listen(443);
```
Then how to make ws or wss work with https? Please @kudos

**Comment by DBozhinovski** [comment]
I ran into a similar issue myself a few days ago. While not ideal, I do have a solution:

From the source of koa-websocket (index.js, lines 43-53):

```
module.exports = function (app) {
  const oldListen = app.listen;
  app.listen = function () {
    debug('Attaching server...');
    app.server = oldListen.apply(app, arguments);
    app.ws.listen(app.server);
    return app.server;
  };
  app.ws = new KoaWebSocketServer(app);
  return app;
};
```
koa-websocket attaches a .ws object to app, which in turn has .listen method. That's exactly the method we need to kind of monkey-patch to hack https into this. So, instead of using listen directly (which makes websockets work on top of koa), can use a workaround:

```
app.listen = () => {
  const server = http.createServer(app.callback()).listen(host.port);
  app.ws.listen(server);
  if (process.env.NODE_ENV === 'production') {
    const sslServer = https.createServer(SSL, app.callback()).listen(443);
    app.ws.listen(sslServer);
  }
};

app.listen();
```
Haven't tested this on a server yet, but it works locally.

**Comment by SteveCruise** [comment]
@DBozhinovski Thank you very very much, great answer. I know how to do it now.

**Comment by stefanb2** [comment]
Just ran into the same issue and found out that the solution in https://github.com/kudos/koa-websocket/issues/29#issuecomment-296473014 does not work for `koa-websocket@4.0.0`, I guess because PR #28 got merged.

Here is the updated version which works for me:

```javascript
const Koa        = require('koa'),
      http       = require('http'),
      webSockify = require('koa-websocket'),
      app        = new Koa();
...
webSockify(app);
...
const server = http.createServer(app.callback());
...
// attach WebSockets to same server
app.ws.listen({
    server: server,
});

// start server
server.listen(port);
```

**Comment by Kenhuey** [comment]
> Just ran into the same issue and found out that the solution in [#29 (comment)](https://github.com/kudos/koa-websocket/issues/29#issuecomment-296473014) does not work for `koa-websocket@4.0.0`, I guess because PR #28 got merged.
> 
> Here is the updated version which works for me:
> 
> ```js
> const Koa        = require('koa'),
>       http       = require('http'),
>       webSockify = require('koa-websocket'),
>       app        = new Koa();
> ...
> webSockify(app);
> ...
> const server = http.createServer(app.callback());
> ...
> // attach WebSockets to same server
> app.ws.listen({
>     server: server,
> });
> 
> // start server
> server.listen(port);
> ```

2021.11.13 Still work :)
