### ISSUE TITLE
Update ws package

### ISSUE THREAD

**Issue by pyros2097** [kudos/koa-websocket#40]
The ws package's latest version is 5.1.1. It would we great if it was updated to the latest.

**Comment by DeeSnow97** [comment]
This is not just a feature request, it's a security issue. Anything below ws@3.3.1 is insecure.

Source: https://nodesecurity.io/advisories/550

**Comment by kudos** [comment]
@DeeSnow97 thanks for the ping on this, I've just published 5.0.0 to take care of it.
