### ISSUE TITLE
npm is a dependency of this project 🤔

### ISSUE THREAD

**Issue by robertrossmann** [kudos/koa-websocket#41]
As of [this commit](https://github.com/kudos/koa-websocket/commit/a12987ec2871d0c7d11bc1cd29e030b322933a7e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R30), `npm` is now a dependency of `koa-websocket`.

I don't believe this was intentional and now it's causing all installations of this package to also include `npm` itself.

**Comment by kudos** [comment]
Ergh, I ran what `npm` suggests when it's outdated without really thinking about it. I've pushed 5.0.1 removing it again.

**Comment by robertrossmann** [comment]
Perfect, thanks! 👍
