### ISSUE TITLE
Update to ws 6.0.0

### ISSUE THREAD

**Issue by lfairy** [kudos/koa-websocket#43]
ws is now up to version 6.0, but koa-websocket still depends on 5.2.

**Comment by Gentlee** [comment]
@lfairy man don't use this lib, use pure ws.

```
const WebSocketServer = require('ws').Server;
const Koa = require('koa');

const app = new Koa();
const server = app.listen(process.env.PORT);
const ws = new WebSocketServer({ server });
```

**Comment by jhpratt** [comment]
@Gentlee How would that work when you need to `export` the websocket server as well? Note that I can't just `export` it, as it's called after an asynchronous function (namely one to create tables in a database). Until top-level `await` becomes a thing, this seems damn near impossible.

**Comment by shellscape** [comment]
@Gentlee that's a teensy bit contrived. there's a lot of heavy lifting that this lib tackles that will have to be re-implemented by using `ws` directly.

**Comment by Gentlee** [comment]
@shellscape this lib is a piece of crap.

**Comment by RWOverdijk** [comment]
@Gentlee Did you write something better? Or should I take your comment with a pinch of salt?

**Comment by nmeylan** [comment]
@Gentlee comment saved my day because I needed to access to WebSocketServer instance directly and this lib does not expose it.
