### ISSUE TITLE
can't use koa-route

### ISSUE THREAD

**Issue by Hi-Rube** [kudos/koa-websocket#5]
node v4.1
koa 1.1.2
koa-route 2.4.2

websocket can connected , but can't send the message

**Comment by kudos** [comment]
It uses koa-route for the tests which still pass (see if they pass for you with `npm test`), including opening the connection and sending/receiving messages. Can you provide a minimal sample of the failure?

**Comment by kudos** [comment]
@Hi-Rube closing this. Feel free to re-open if you provide more details.
